on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      node-version:
        required: true
        type: string
      webapp-name:
        required: true
        type: string

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  webapp-deploy:
    name: Deploy Code - ${{ inputs.environment }}
    continue-on-error: false
    runs-on: ubuntu-latest
    environment:
      # Use the input to set the environment
      name: ${{ inputs.environment }}
      url: "https://${{ inputs.webapp-name }}-${{ inputs.environment }}.azurewebsites.net/"

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: npm install
      run: |
        npm install
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.webapp-name }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: ${{ inputs.environment }}
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3.1
      with:
        url: https://${{ inputs.webapp-name }}-${{ inputs.environment }}.azurewebsites.net/|https://${{ inputs.webapp-name }}-${{ inputs.environment }}.azurewebsites.net/user/rob-derosa
        follow-redirect: false
        max-attempts: 3
        retry-delay: 5s
